github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
theme: jekyll-theme-slate
gfm_quirks: paragraph_end
github:
  repository_url: "https://github.com/nickshin/bookmark_tools"
